---
name: hds
services:
  redis:
    image: redis:alpine
    container_name: hds-redis
    profiles:
      - redis
      - media
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
    - "./Docker/Redis/redis.conf:/usr/local/etc/redis/redis.conf"
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.redis.rule=Host(`hds.redis`)"
      - "traefik.http.routers.redis.entrypoints=http"
      - "traefik.http.services.redis.loadbalancer.server.port=6379"

  paperless-ngx:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: hds-paperless
    profiles:
      - paperless
      - media
    ports:
      - 8000:8000
    depends_on:
      - redis
    volumes:
      - "${PAPERLESS_DATA_DIR}:/usr/src/paperless/data"
      - "${PAPERLESS_MEDIA_DIR}:/usr/src/paperless/media"
    environment:
      - PAPERLESS_ADMIN_USER=${PAPERLESS_ADMIN_USER}
      - PAPERLESS_ADMIN_PASSWORD=${PAPERLESS_ADMIN_PASSWORD}
      - PAPERLESS_REDIS=redis://redis:6379
      - USERMAP_UID=${APP_UID}
      - USERMAP_GID=${APP_GID}
      - PAPERLESS_TIME_ZONE=Europe/Berlin
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.paperless.rule=Host(`hds.paperless`)"
      - "traefik.http.routers.paperless.entrypoints=http"
      - "traefik.http.services.paperless.loadbalancer.server.port=8000"

  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: hds-jellyfin
    profiles:
      - jellyfin
      - media
    volumes:
      - ${JELLYFIN_CACHE_DIR}:/cache
      - ${JELLYFIN_MEDIA_DIR}:/media
      - hds-jf-config:/config
    ports:
      - 8096:8096
    environment:
      - UID=${APP_UID}
      - GID=${APP_GID}
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`hds.jellyfin`)"
      - "traefik.http.routers.jellyfin.entrypoints=http"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"

  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: hds-files
    profiles:
      - files
      - media
    ports:
      - "8099:80"
    volumes:
      - ${JELLYFIN_MEDIA_DIR}:/srv/Media
      - ${FILEBROWSER_ROOT}:/database
      - ${FILEBROWSER_DATA_DIR}:/srv
    environment:
      - FB_DATABASE=/database/filebrowser.db
      - FB_CONFIG=/database/filebrowser.json
      - UID=${APP_UID}
      - GID=${APP_GID}
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.files.rule=Host(`hds.files`)"
      - "traefik.http.routers.files.entrypoints=http"
      - "traefik.http.services.files.loadbalancer.server.port=80"

volumes:
  hds-jf-config:

networks:
  default:
    name: ${COMPOSE_NETWORK}
    external: ${COMPOSE_NETWORK_EXT}
    driver: bridge