---
name: hds
services:
  paperless-ngx:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: hds-paperless
    profiles:
      - paperless
      - media
      - external
    ports:
      - 8000:8000
    depends_on:
      - redis
    volumes:
      - "${PAPERLESS_DATA_DIR}:/usr/src/paperless/data"
      - "${PAPERLESS_MEDIA_DIR}:/usr/src/paperless/media"
    environment:
      - PAPERLESS_ADMIN_USER=${PAPERLESS_ADMIN_USER}
      - PAPERLESS_ADMIN_PASSWORD=${PAPERLESS_ADMIN_PASSWORD}
      - PAPERLESS_REDIS=redis://redis:6379
      - USERMAP_UID=${APP_UID}
      - USERMAP_GID=${APP_GID}
      - PAPERLESS_TIME_ZONE=Europe/Berlin
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.paperless.rule=Host(`hds.paperless`)"
      - "traefik.http.routers.paperless.entrypoints=http"
      - "traefik.http.services.paperless.loadbalancer.server.port=8000"

  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: hds-jellyfin
    profiles:
      - jellyfin
      - media
      - external
    volumes:
      - ${JELLYFIN_CACHE_DIR}:/cache
      - ${JELLYFIN_MEDIA_DIR}:/media
      - hds-jf-config:/config
    ports:
      - 8096:8096
    environment:
      - UID=${APP_UID}
      - GID=${APP_GID}
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`hds.jellyfin`)"
      - "traefik.http.routers.jellyfin.entrypoints=http"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"

volumes:
  hds-jf-config:

networks:
  default:
    name: ${COMPOSE_NETWORK}
    external: ${COMPOSE_NETWORK_EXT}
    driver: bridge