global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090', 'hds-prometheus:9090']

  - job_name: 'traefik'
    static_configs:
      - targets: ['hds-traefik:8080']

  - job_name: 'docker'
    static_configs:
      - targets: ['hds-docker:9323']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['localhost:9100', 'hds-node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['hds-cadvisor:8080']